name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        run: |
          sudo apt-get install -y awscli
          aws --version

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 619071345457.dkr.ecr.us-west-2.amazonaws.com

      - name: Build and Push Docker Image
        run: |
          docker build -t santosh .
          docker tag santosh:latest 619071345457.dkr.ecr.us-west-2.amazonaws.com/santosh:latest
          docker push 619071345457.dkr.ecr.us-west-2.amazonaws.com/santosh:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Configure kubectl
        run: |
          aws eks --region us-west-2 update-kubeconfig --name my-eks-cluster

      - name: Deploy to EKS
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
