apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: 619071345457.dkr.ecr.us-west-2.amazonaws.com/santosh:latest
        ports:
        - containerPort: 8000
